### PR TITLE
Pythonic v0.1.2 release

### PR DESCRIPTION
**Pull request by cbm755**

### CODE REVIEW

**Comment by cbm755** [comment]
@Vipul-Cariappa here's the far end of the release: the meta data update for packages.octave.org

**Comment by cbm755** [comment]
@siko1056 I don't think we have enough Python for our tests to pass on this CI...  I *think* its ok to merge anyway, but figured I would double-check before merging.

Errors:
```
Run pkgs=" pythonic "


## Test package 'pythonic'


Resolve locally build package index
Resolve package dependencies
Install dependency:  doctest@0.8.0
Run: pkg install   pythonic@0.1.2
ERROR: pkg install -verbose pythonic@0.1.2
  mkdir (/tmp/oct-SfpUCg)
  untar (/tmp/oct-kgvZC8/octave-pythonic-0.1.2.tar.gz, /tmp/oct-SfpUCg)
  make: Entering directory '/tmp/oct-SfpUCg/octave-pythonic-0.1.2/src'
  Makefile:118: *** The header file <Python.h> is not found, you may need to install Python header files and development libraries.  Stop.
  make: Leaving directory '/tmp/oct-SfpUCg/octave-pythonic-0.1.2/src'
```

**Comment by siko1056** [comment]
Thanks @cbm755 for not giving up :+1: 

Is there anything to make it easier to solve such issues?

**Review by siko1056 — APPROVED** [review]
LGTM :+1:

**Comment by cbm755** [comment]
> Is there anything to make it easier to solve such issues?

Thanks, but I think it was mostly PEBKAC in this case!

**Pull request merged**
