### PR TITLE
Add Dynare

### PR DESCRIPTION
**Pull request by svillemot**
Note that Dynare cannot be installed through `pkg`. So I added a download link, and did not provide any `versions` entry.

Please let me know if this is not the correct way of doing it.

### CODE REVIEW

**Comment by siko1056** [comment]
Hi @svillemot , Thanks for considering Octave packages to advertise Dynare.  Your case is rather new.  It is okay, as you said, that Dynare is not installable by `pkg`.  However, a version is considered as useful for this package platform to inform users about updates, getting ranked high (in default order) as active project (and to not fail the test pipeline, the last one is a joke of course :sweat_smile: ).

As without version your package will get added (most likely, I never tried) to the bottom of the page and only be find able via the search function.  If you think that helps to achieve your goals, let us merge your package as is.  If you can spare the effort of maintaining the Dynare updates in this platform, it might be helpful for users to get attention to Dynare.

**Comment by svillemot** [comment]
Also, the minimal Octave version required is 5.1.0.

**Comment by siko1056** [comment]
Thanks for the input.  I also needed to play a bit around to see what is the bare minimum necessary.

**Comment by siko1056** [comment]
I hope the result is now satisfying? https://gnu-octave.github.io/packages/dynare/

**Comment by svillemot** [comment]
Thanks for your help, it looks pretty good!

I’ll take of future updates when new versions are released.

**Comment by svillemot** [comment]
I just noticed that the download link now appears two times. I wonder whether we should remove the one in the links list.

**Comment by siko1056** [comment]
Maybe just a final hint regarding the "pkg" message.  Only if the package claims to be installable by "pkg", one can add the "pkg" dependency and this message disappears.

Let me strip the download link at the bottom.

**Comment by siko1056** [comment]
I invited you to the GitHub organization, then you can merge your updates directly yourself.

**Comment by svillemot** [comment]
Thanks! I’ve accepted the invitation.

**Pull request merged**
