### PR TITLE
Update octclip.yaml: release 2.0.2

### PR DESCRIPTION
**Pull request by jgpallero**
Update octclip.yaml in order to redirect to te Bitbucket repository

### CODE REVIEW

**Comment by siko1056** [comment]
Many thanks for maintaining the octclip package and release @jgpallero ! 🙂 

In contrast to Octave Forge, you can release your package at your own pace.  I invited you to the "gnu-octave" organization of GitHub, which gives you access to run the package check pipeline on your own, please errors and finally merge the updates to the "main" branch which will go live with a five minutes delay.

If you have any questions or doubts, please reach out to me.

**Comment by jgpallero** [comment]
> Many thanks for maintaining the octclip package and release @jgpallero ! slightly_smiling_face
> 
> In contrast to Octave Forge, you can release your package at your own pace. I invited you to the "gnu-octave" organization of GitHub, which gives you access to run the package check pipeline on your own, please errors and finally merge the updates to the "main" branch which will go live with a five minutes delay.
> 
> If you have any questions or doubts, please reach out to me.

Dear Kai,

I can see that, although I put de octclip.png icon in the doc/ folder and I refer to it in the *.yaml file (https://bitbucket.org/jgpallero/octclip/src/master/doc/octclip.png), it does not appear in https://gnu-octave.github.io/packages/octclip/. What am I doing wrong?

Thanks

**Comment by siko1056** [comment]
Thank you for the release.  I pushed an additional changeset https://github.com/gnu-octave/packages/commit/2aa57d682aca9f2c2ccb59df016d154810bfd031 which uses the raw image url of the image in your repository and the checksum for the installation file.

**Comment by siko1056** [comment]
Thank you for merging this PR and sorry for the late reply.  Yes, the checksum is unique for each release you create.  You can determine the sha256 checksum like explained here: https://github.com/gnu-octave/packages/blob/main/CONTRIBUTING.md#-individual-field-explanations

```
sha256sum octclip-2.0.2.tar.gz
```

But if you forget this checksum it is no big deal, I can add it later.  Future `pkg`-tool version might use this checksum to verify the file integrity before the installation.  But the current ´pkg´-tool ignores this information.

Another feature I want to mention is, that you can list multiple releases of your package.  Some users want to use older versions of your package, for example.  This was not possible with Octave Forge.  In Octave Packages it is not necessary to delete any information, just add your latest release at the TOP of the versions-list and the `pkg`-tool will always pick the latest version.

Again many thanks for the package maintenance.

**Pull request merged**
