### PR TITLE
Create pkg-internal-flow.yaml

### PR DESCRIPTION
**Pull request by aumpierre-unb**
This package is a set of functions designed for solving problems of internal fluid flow.

### CODE REVIEW

**Comment by siko1056** [comment]
Thank you for your new contribution :slightly_smiling_face: :+1: 

Your repository is currently located at:

- https://github.com/aumpierre-unb/Internal-Flow

not as written in the YAML file:

- https://github.com/gnu-octave/pkg-internal-flow/

Do you want
1. to keep you repository at the original location, then please make a GitHub release and update the YAML file.
2. relocate the repository to the second url, then you have to transfer the ownership of the repo there.  Please read: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repositoryhttps://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by siko1056** [comment]
@aumpierre-unb please top pushing to main and work with us on this pull request.

I will reset all your changes on main.  Main is a stable branch being exposed to the public and pushing unstable tests there breaks package installation.  You were the first to break this rule, now it should be enforced by the GitHub settings.

Again, please communicate with us.  Why do you need to push to the main branch directly and waste your time?

**Comment by siko1056** [comment]
@aumpierre-unb please talk with us.  You have been temporarily removed from the gnu-octave organization as you are behaving rude and misuse the power granted to you vandalizing he package repository creating many branches without purpose.

Please ask what problems you are facing?

**Comment by aumpierre-unb** [comment]
I'm not trying to vandalize anything. I was trying to include my package
and fix all bugs in order to make it work properly. Sorry for the trouble.
Just drop it. Rds

**Comment by siko1056** [comment]
Thanks for your reply and sorry for the drastic measure, but things became worse and worse in the past 2 hours.

I notice something seems to not work for you, maybe our documentation is not yet sufficient.  Please explain what you do not understand about my previous questions?

https://github.com/gnu-octave/packages/pull/114#issuecomment-1152954894

**Comment by aumpierre-unb** [comment]
Don't worry. Maybe some other day, too tired to start it all over.

**Comment by siko1056** [comment]
Ok, again sorry it caused frustration on both sides today.

I am really willing to help, lets have a fresh start another day :slightly_smiling_face:

**Pull request closed without merging**
