### PR TITLE
Add statistics-bootstrap package via upload

### PR DESCRIPTION
**Pull request by acp29**

### CODE REVIEW

**Comment by siko1056** [comment]
@acp29 Thank you for the new package :slightly_smiling_face:

I added some comments to the commit 0c06b4703e668aea364e4c8db7fbe57cc576b382.  Do you have time to work on this?

**Comment by siko1056** [comment]
I apply some fixes to the package file.  Again thanks for the contribution :slightly_smiling_face: :+1:

**Comment by siko1056** [comment]
@acp29 One more comment, it took quite some time to change CRLF back to LF only (unix style) to have a consistent style in this system.  Is there a particular need for CRLF line endings?

https://github.com/gnu-octave/statistics-bootstrap/commit/d7e6e60949224040764872e1e569485d72a122e8

**Comment by acp29** [comment]
Hi @siko1056, sorry about the line break changes. I noticed the files looked funky in Windows text editors so I changed the line break character in Xcode (which I use to edit code) not realising that you needed a specific characters. I see it now at https://gnu-octave.github.io/packages/.

**Comment by acp29** [comment]
@siko1056, I'll clone the the fixed yaml file from your gnu-octave packages. How did you find the SHA256?

I noticed a harmless but annoying bug when installing the package with the pkg install command in that it finds no usable help info in rng_state.m:

octave:12> pkg install "https://github.com/gnu-octave/statistics-bootstrap/archive/refs/tags/v2.9.tar.gz"
warning: doc_cache_create: unusable help text found in file 'rng_state'
warning: called from
    doc_cache_create>handle_function at line 98 column 5
    doc_cache_create>create_cache at line 118 column 36
    gen_doc_cache_in_dir>@<anonymous> at line 150 column 16
    doc_cache_create>gen_doc_cache_in_dir at line 151 column 9
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 823 column 5
    install at line 235 column 7
    pkg at line 568 column 9
    
I've fixed this now for the development version so I'll release a bug fix and update the yaml file on the forked document.

**Comment by acp29** [comment]
No worries, all fixed (SHA256 too, I was getting mixed up between the Hash and the commits!)

**Comment by siko1056** [comment]
Yes the sha256 checksum refers to the released package archive, not a git commit.  This serves in future pkg versions for integrity checks.

Feel free and make any time a release 🙂 If you need any help, please just ping me.

**Pull request merged**
