### PR TITLE
New package octave-cfitsio

### PR DESCRIPTION
**Pull request by lostbard**

### CODE REVIEW

**Comment by siko1056** [comment]
@lostbard Thanks for the new package :slightly_smiling_face: 

Do you really want to keep the "octave-"-prefix in the package name?  https://sourceforge.net/p/octave-cfitsio/code/ci/default/tree/DESCRIPTION

Basically, this is not a problem.  In the future users will have to always type and remember this prefix as well:
```
pkg install octave-cfitsio
```
The repo can keep this name, but the package itself may perfectly take a shorter name :wink:

**Comment by lostbard** [comment]
@siko1056 yeah - i should have thought  a little more about that and it would probally make more sense

**Comment by siko1056** [comment]
Then shall I release this package as it is?

**Comment by lostbard** [comment]
New version with short name

**Pull request merged**
