### PR TITLE
New package mccabe-thiele

### PR DESCRIPTION
**Pull request by aumpierre-unb**
new pkg proposal
first release
chemical engineering
unit operations

### CODE REVIEW

**Comment by siko1056** [comment]
@aumpierre-unb Many thanks for your new package and I am very sorry for the trouble with the checks.  In this repository, we try to keep files with "Unix line ending" = "\n" = <LF>.  Many text editors (e.g. Notepad++) support this feature to control the line ending.

https://en.wikipedia.org/wiki/Newline#Representation

If you need help with this, please reach out to me.

**Comment by aumpierre-unb** [comment]
Thank you again. I can't understand what was wrong. I followed (tried to follow!) the same pattern of other .yaml but it didn't worked.

**Comment by aumpierre-unb** [comment]
No problem at all, I couldn't figure it it out...

**Comment by siko1056** [comment]
Basically everything you did was perfectly right.  Like written before it was an End-of-Line problem, tricky, but necessary to keep the repository in a unique shape.

If your editor supports End-of-Line settings, try using UNIX style and this problem should be gone.

**Pull request merged**
