### PR TITLE
bumped up the version and move to github

### PR DESCRIPTION
**Pull request by jendralhxr**
https://github.com/ltfat/ltfat/releases/tag/v2.5.0

### CODE REVIEW

**Comment by siko1056** [comment]
Thank you very much for the release @jendralhxr .  Are you a ltfat developer / maintainer?

The provided tarball is not a valid Octave package.  It seems that for previous releases this directory seems to have been used https://github.com/ltfat/ltfat/tree/master/mat2doc/mat, but I do not have more insight into this project.

Long story short.  With this PR ltfat becomes unusable for Octave, even though the version claims to be newer.

How would you like to proceed?

**Comment by jendralhxr** [comment]
I am not developer nor maintainer of ltfat, just an avid user.

The newer version is fully functional though, but instead of the usual **pkg load** invocation, we need to use **ltfatstart**.
Most likely the current developer (allthatsounds) did such approach to appeal to both Matlab and Octave communities, but broke **pkg install** compatibility in the process.
I don't think repacking the current release to conform with **pkg** will be that hard. Let's suggest allthatsounds to make proper Octave package and then we can refer to it (or I can make a PR in ltfat repo).

In the meantime, you can close decline this PR. Thank you for your time.

**Comment by jendralhxr** [comment]
Please refer to the octave-forge package in https://github.com/ltfat/ltfat/releases/download/v2.5.0/ltfat-2.5.0-of.tar.gz

**Comment by siko1056** [comment]
Thank you @jendralhxr for observing the "-of" package.  I overlooked that one and it works perfectly :tada: 

To make the CI pass,I relaxed the test suite regarding the package name in lower case 6d2ad4cf91102759655d888565945fd037a5f4f4. The current Octave package tool also ignores the case.

**Comment by jendralhxr** [comment]
Thanks @siko1056

**Pull request merged**
