### PR TITLE
New package: "internal-fluid-flow"

### PR DESCRIPTION
**Pull request by siko1056**
https://octave.discourse.group/t/candidate-for-internal-fluid-flow-package/2968/5

@aumpierre-unb

### CODE REVIEW

**Comment by aumpierre-unb** [comment]
I've just included a COPYING file. It seems to me that the lack of this file was producing an error. The content of this file is the same of the initial commit LICENSE, however Octave demands a file named COPYING.

**Comment by aumpierre-unb** [comment]
Ok thanks! think it is alright now.

**Comment by siko1056** [comment]
Sorry for bothering again.  Recreating the release must be done with the new commit (COPYING) included:

image

This "one commit since the release must be included.  Please delete the release and run from your local machine and repository the following command
```
git push --delete origin v0.0.1
```
Then make a new release with the latest commit including the COPYRIGHT file.

You can test if everything is fine by installing the package in your Octave:
```
pkg install https://github.com/aumpierre-unb/Internal-Fluid-Flow-for-GNU-Octave/archive/refs/tags/v0.0.1.tar.gz
```
If the command above succeeds without errors, Octave Packages is ready to receive your package :slightly_smiling_face:

**Comment by aumpierre-unb** [comment]
There must be something and I my missing. The COPYING file is present in the repository but does not show up in the source assets. I noticed that some authors rename the initial commit LICENSE to COPYING. It did not work for me. I also tried including both LICENSE and COPYING, LICENSE and COPYING and COPYRIGHT (as you suggested, only in this case github does not recognizes COPYRIGHT as valid file name for the license and the content must be copied/pasted instead of automatically generated by github), only COPYING, only LICENSE, only COPYRIGHT. It turns out in all cases the source assets have a LICENSE instead of a COPYING. Any tips??

**Comment by siko1056** [comment]
The issue is only about improper usage of GitHub.  I know this is a little confusing in the beginning and I am willing to help.

First step.  We have to get rid of your current v0.0.1 release.  How to do it?

1. Delete the release as before.
2. Run  from your local machine and repository the following command

        git push --delete origin v0.0.1

Then report back and I look if we are at this step again.

**Comment by siko1056** [comment]
@aumpierre-unb great, now step two and we are there.  This tag must vanish:

https://github.com/aumpierre-unb/Internal-Fluid-Flow-for-GNU-Octave/tags

**Comment by aumpierre-unb** [comment]
I deleted it from the website.

**Comment by siko1056** [comment]
Perfect, now you can create the v0.0.1 release again, but make very sure, that the tag is created from the latest changeset:

image

**Comment by aumpierre-unb** [comment]
It seems to be working now. Release v0.0.1 was successfully installed in octave from the repository. Thank you for your help, would do it by myself. Are there further instructions?

**Comment by siko1056** [comment]
@aumpierre-unb congratulation, your package is now released and in about 10 minutes installable via `pkg install -forge internal-fluid-flow` :tada: 

https://gnu-octave.github.io/packages/internal-fluid-flow/

I will add you to the gnu-octave organization and you can update your package at your own pace.  If you have any trouble, please feel free to reach out to me again.

**Comment by aumpierre-unb** [comment]
Thank you very much again! That was way too tricky for me. Would never do it without your help.

**Comment by aumpierre-unb** [comment]
In the following days I'll be working on minor problems that do not affect the performance of .m files at all. When I find it is time for a new release, I simply build a v0.0.2 and the package will update/include the new release or the processes restarts form the beginning?

**Comment by siko1056** [comment]
@aumpierre-unb no worries, I am sure you will quickly find into the workflow now:

1. Check the latest version of your package to work `pkg install https://github.com/aumpierre-unb/Internal-Fluid-Flow-for-GNU-Octave/archive/refs/heads/main.tar.gz`
2. Tag the release
3. Add the release line to Octave packages.  The maintainer of the statistics-bootstrap packages does this with ease almost every week :wink: For example: https://github.com/gnu-octave/packages/pull/120/files

**Comment by aumpierre-unb** [comment]
Hi, sorry to bother again. I did not yet get how to properly make a release.
I updated the m-files and included a NEWS, produced a new release under a
new tag ("v0.0.2") and produced the yaml file.
Soon after I received an email appointing errors on both the yaml file and
the m-files.
According to the error logs, the "description line" in the yaml file was
too long, so I cut it in two lines.
Also there was a problem at the ending of functions. Apparently it was due
to a missing line after the endfunction at one of the m-file. It is fixed
and rebuilt the yaml file with updated hash string.
Is this the correct procedure? If not, what was the problem?
I must now upload the yaml file to repositories/packages or
repositories/packages-sandbox??
Also, release "v.0.0.1" disappeared and I can't explain how it happened. I
believe I only acted on the tag "v0.0.2"... I understand it should
preferably not be eliminated and I am sorry for that.
Thanks

**Pull request merged**
