### PR TITLE
New package: ONSAS

### PR DESCRIPTION
**Pull request by jorgepz**
Add yml file for https://github.com/ONSAS/ONSAS.m/ package

### CODE REVIEW

**Comment by siko1056** [comment]
Thank you for your new package, ONSAS looks very interesting :slightly_smiling_face: :+1: 

I will add your package after two changes:
1. Please rename `ONSAS.yml` to `ONSAS.yaml` for consistency.
2. To keep the YAML files in shape, please restrict the line length to 80 characters.  This will not have any impact on the final output (newlines are ignored):
   ```
   description: >-
     ONSAS is an Open Nonlinear Structural Analysis Solver.  It is a GNU-Octave
     code for static/dynamic and linear/non-linear analysis of structures
     including, solids, beams, truss or plane structures.
   ```

**Comment by jorgepz** [comment]
Thank you! I've just made the changes.

**Comment by siko1056** [comment]
Thanks for the changes @jorgepz :+1: I gave the package a more thorough review and unfortunately a few more changes are necessary (the default values from pkg-example looked too correct, but should match ONSAS I think :sweat_smile: ).  Then I will add the package.

Another thing is that Octave's pkg tool is not able to install ONSAS yet.

```
>> pkg install https://github.com/ONSAS/ONSAS.m/archive/refs/tags/v0.2.4.tar.gz
error: package is missing file: COPYING
error: called from
    install>verify_directory at line 352 column 7
    install at line 121 column 9
    pkg at line 568 column 9
```

To resolve that issue, please rename `COPYING.txt` to `COPYING` in your repo https://github.com/ONSAS/ONSAS.m and make a new release (e.g. v0.2.5).  That issue is related to ONSAS and not a hindrance to be added to this package list :wink:

**Comment by jorgepz** [comment]
thanks. Yes sure, it is better to get the whole process validated. We will be publishing the next release probably next week and will update the yaml file after that!

**Comment by siko1056** [comment]
Thanks again for the changes. I created https://github.com/ONSAS/ONSAS.m/pull/396 for another installation error
```
>> pkg install https://github.com/ONSAS/ONSAS.m/archive/refs/heads/master.tar.gz
error: the DESCRIPTION file must have a Categories field, when no INDEX file is given
error: called from
    install>write_index at line 694 column 5
    install>copy_files at line 599 column 7
    install at line 231 column 7
    pkg at line 568 column 9
```

During the development, you can try to install the head of your development branch with Octave pkg to get rid of the last cosmetic problems:
```
pkg install https://github.com/ONSAS/ONSAS.m/archive/refs/heads/master.tar.gz
```

**Comment by jorgepz** [comment]
thanks for the pkg install command for the development phase. I found other functions docs warnings. I am closing the PR and reopen it after the new release is done and the warnings are solved. Thanks!

**Comment by siko1056** [comment]
Great, I am looking forward for your next PR.

**Comment by jorgepz** [comment]
We've just updated ONSAS and we might now have solved the pkg errors. I propose reopening the PR.

**Comment by siko1056** [comment]
Thank you very much for the new package :slightly_smiling_face: :+1:

**Pull request merged**
