### PR TITLE
Symbolic 3.2.0

### PR DESCRIPTION
**Pull request by cbm755**
New release.  Also belatedly adjust the URLs because Symbolic moved into the gnu-octave/ namespace

### CODE REVIEW

**Comment by mmuetzel** [comment]
Thank you for updating the package.

**Comment by mmuetzel** [comment]
I noticed that you added a tarball to the GitHub releases in the past. E.g., https://github.com/gnu-octave/symbolic/releases/download/v3.1.1/symbolic-3.1.1.tar.gz

I didn't find the corresponding release tarball for version 3.2.0. Is that intentional?

**Comment by cbm755** [comment]
Not intentional, fixed.  (the official tarball is on sourceforge but can't hurt to mirror)

**Comment by mmuetzel** [comment]
Thank you for mirroring the tarball also on GitHub.

I noticed that it was missing when I tried to update MXE Octave to package the newer version of the symbolic package (e.g., for Octave for Windows). At some point, the build rules in MXE Octave were change to download the tarball from GitHub. IIRC, that was done because downloading it from SourceForge was sometimes slow or unreliable.
The existing build rules in MXE Octave seem to be working with the new version now, too. 🎉

While testing the new version, I noticed that it prints something like `Symbolic pkg v3.1.1+:` on first use. Also the folder that Octave selects to install the package contains `symbolic-3.1.1+`. I haven't checked. But maybe that is coming from the `DESCRIPTION` file. That file contains a line `Version: 3.1.1+`. (Also, the `Date` value might be wrong.)
Should that be updated to `3.2.0` (or `3.2.1` in case that requires a new release)?

**Comment by cbm755** [comment]
Oops, yeah that'll need a new release, will do 3.2.1 later today, thanks

**Pull request merged**
