### PR TITLE
bim release 1.1.6

### PR DESCRIPTION
**Pull request by carlodefalco**
release 1.1.6 of bim package

### CODE REVIEW

**Comment by siko1056** [comment]
Thank you @carlodefalco for the package updates :slightly_smiling_face: :+1: 

Regarding the msh package, there seems to be a minor problem in the test functions, see the excerpt from the test log:

```
2022-07-22T05:05:12.5784553Z ##[group]Run: pkg test      msh@1.0.11
2022-07-22T05:05:12.5961181Z Testing functions in package 'msh':
2022-07-22T05:05:12.6079950Z 
2022-07-22T05:05:12.6080375Z Integrated test scripts:
2022-07-22T05:05:12.6080603Z 
2022-07-22T05:05:12.6918693Z   ..ve/api-v57/packages/msh-1.0.11/msh2m_geometrical_properties.m  pass    1/1   
2022-07-22T05:05:12.7395245Z   ../.local/share/octave/api-v57/packages/msh-1.0.11/msh2m_gmsh.m  pass    0/1   
2022-07-22T05:05:12.7395689Z                                                                    FAIL    1
2022-07-22T05:05:12.7597306Z   ..tave/api-v57/packages/msh-1.0.11/msh2m_join_structured_mesh.m  pass    1/1   
2022-07-22T05:05:12.7744449Z   ..are/octave/api-v57/packages/msh-1.0.11/msh2m_nodes_on_sides.m  pass    1/1   

[...]

2022-07-22T05:05:12.9398839Z Failure Summary:
2022-07-22T05:05:12.9398999Z 
2022-07-22T05:05:12.9399548Z   ../.local/share/octave/api-v57/packages/msh-1.0.11/msh2m_gmsh.m  pass    0/1   
2022-07-22T05:05:12.9407665Z                                                                    FAIL    1
2022-07-22T05:05:12.9407881Z 
2022-07-22T05:05:12.9408006Z Summary:
2022-07-22T05:05:12.9408152Z 
2022-07-22T05:05:12.9408261Z   PASS                               28
2022-07-22T05:05:12.9408546Z   FAIL                                1
2022-07-22T05:05:12.9408712Z 
2022-07-22T05:05:12.9408890Z See the file /tmp/fntests.log for additional details.
2022-07-22T05:05:12.9409136Z 
2022-07-22T05:05:12.9409257Z 9 (of 21) .m files have no tests.
2022-07-22T05:05:12.9409431Z 
2022-07-22T05:05:12.9409631Z Please help improve Octave by contributing tests for these files
2022-07-22T05:05:12.9410143Z (see the list in the file /tmp/fntests.log).

[...]

2022-07-22T05:05:13.0108439Z ##[group]Show: fntests.log
2022-07-22T05:05:13.0208500Z # >>>>>  new test file
2022-07-22T05:05:13.0208828Z # ?????  no tests in file
2022-07-22T05:05:13.0209131Z # !!!!!  test had an unexpected result
2022-07-22T05:05:13.0209721Z # -----  test was skipped
2022-07-22T05:05:13.0210419Z # *****  code for the test
2022-07-22T05:05:13.0210591Z 
2022-07-22T05:05:13.0210742Z # Search for the unexpected results in the file
2022-07-22T05:05:13.0211117Z # then page back to find the filename which caused it.
2022-07-22T05:05:13.0211495Z # The result may be an unexpected failure (in which
2022-07-22T05:05:13.0211856Z # case an error will be reported) or an unexpected
2022-07-22T05:05:13.0212224Z # success (in which case no error will be reported).
2022-07-22T05:05:13.0212879Z >>>>> processing /home/jovyan/.local/share/octave/api-v57/packages/msh-1.0.11/msh2m_geometrical_properties.m
2022-07-22T05:05:13.0213512Z >>>>> processing /home/jovyan/.local/share/octave/api-v57/packages/msh-1.0.11/msh2m_gmsh.m
2022-07-22T05:05:13.0213884Z ***** test
2022-07-22T05:05:13.0214145Z  fid = fopen("circle.geo","w");
2022-07-22T05:05:13.0214458Z  fprintf(fid,"Point(1) = {0, 0, 0, 1};\n");
2022-07-22T05:05:13.0214775Z  fprintf(fid,"Point(2) = {1, 0, 0, 1};\n");
2022-07-22T05:05:13.0215151Z  fprintf(fid,"Point(3) = {-1, 0, 0, 1};\n");
2022-07-22T05:05:13.0215474Z  fprintf(fid,"Circle(1) = {3, 1, 2};\n");
2022-07-22T05:05:13.0215784Z  fprintf(fid,"Circle(2) = {2, 1, 3};\n");
2022-07-22T05:05:13.0216091Z  fprintf(fid,"Line Loop(4) = {2, 1};\n");
2022-07-22T05:05:13.0216412Z  fprintf(fid,"Plane Surface(4) = {4};");
2022-07-22T05:05:13.0216676Z  fclose(fid);
2022-07-22T05:05:13.0216948Z  mesh = msh2m_gmsh("circle","v",0);
2022-07-22T05:05:13.0217238Z  system("rm circle.geo");
2022-07-22T05:05:13.0217531Z  nnodest = length(unique(mesh.t));
2022-07-22T05:05:13.0217828Z  nnodesp = columns(mesh.p);
2022-07-22T05:05:13.0218106Z  assert(nnodest,nnodesp);
2022-07-22T05:05:13.0218372Z !!!!! test failed
2022-07-22T05:05:13.0218740Z 'tmpnam' undefined near line 78, column 22
```

No release blocker, maybe this small issue can be fixed with the next release.

**Comment by carlodefalco** [comment]
Hi, thanks for the merge!

The fails in MSH are due to a missing dependency, they need to have gmsh to be installed on the test machine, I'll see how to check for that and skip the test if not available.

Two more questions

- the function reference links still points to SF, is there a way to move that to github or elsewhere?

- what should I do about the hG repos on SF?

c.

**Comment by siko1056** [comment]
> The fails in MSH are due to a missing dependency, they need to have gmsh to be installed on the test machine

This package https://packages.ubuntu.com/jammy/gmsh?  Octave Packages can handle such installations :wink: I can this if this is the right one.

> - the function reference links still points to SF, is there a way to move that to github or elsewhere?

You can keep on hosting it on SF and I give you access permission, which enables you to upload the files with FileZilla or another SFTP client.  You can of course host the HTML output from the generate_html package on any webserver, but looks quite ugly in my opinion.  A standalone documentation package is not yet available, and it might take some time until I can come up with an automated solution.

> - what should I do about the hG repos on SF?

I would keep them as they are for reference.  There is no urgent need to update them or to remove them.

**Comment by carlodefalco** [comment]
> This package https://packages.ubuntu.com/jammy/gmsh? Octave Packages can handle such installations 😉 I can this if this is the right one.

Yest, that should be the right one!

**Comment by siko1056** [comment]
I made the change #147 , but it does not solve the error.  Also on my system I can reproduce the problem.

First observation is that `tmpnam` existed in Octave 3.8, but has been replaced since Octave 4.0.0 with `tempname`, https://docs.octave.org/v7.1.0/Temporary-Files.html.

A patch was given here: https://savannah.gnu.org/bugs/index.php?59613

Even after fixing this and having gmsh installed I cannot get the test to run :sweat:   I might need to look more closely at what is happening.

**Comment by siko1056** [comment]
Two other issues can be reviewed here: https://octave.space/savannah/?Action=get&Format=HTMLCSS&Title=[octave%20forge]%20(msh)

**Comment by carlodefalco** [comment]
> First observation is that tmpnam existed in Octave 3.8, but has been replaced since Octave 4.0.0 with tempname, https://docs.octave.org/v7.1.0/Temporary-Files.html.

> A patch was given here: https://savannah.gnu.org/bugs/index.php?59613

This should have been already fixed : 

https://github.com/carlodefalco/msh/commit/4fc1c6c78bb5655e9b9abfc08e86c9bbb511eb47#diff-976f677c81ca98695e7b7c978165f786e4994aa6feb6957219259f6fa202f293

**Comment by siko1056** [comment]
I think something is wrong with the msh repo :thinking: 

https://github.com/carlodefalco/msh/commit/06bc6adae4de0f522cbed08a32e986e5db120670

image

**Comment by carlodefalco** [comment]
You are right it seems I committed to upstream rather than origin and messed up things a bit.
I'll fix the release ...

**Comment by carlodefalco** [comment]
> You are right it seems I committed to upstream rather than origin and messed up things a bit. I'll fix the release ...

Actually that is one mistake but there is also another one, I messed up with a few repositories ...
I'm trying to fix all and then make a pull request rather than push directly to this repo (that was unintended the first time around)

**Comment by carlodefalco** [comment]
all tests seem to pass for me now :

```
>> pkg test msh
Testing functions in package 'msh':

Integrated test scripts:

  /Users/carlo/octave/msh-1.0.12/msh2m_geometrical_properties.m .. pass    1/1   
  /Users/carlo/octave/msh-1.0.12/msh2m_gmsh.m .................... pass    1/1   
  /Users/carlo/octave/msh-1.0.12/msh2m_join_structured_mesh.m .... pass    1/1   
  /Users/carlo/octave/msh-1.0.12/msh2m_nodes_on_sides.m .......... pass    1/1   
  /Users/carlo/octave/msh-1.0.12/msh2m_structured_mesh.m ......... pass    1/1   
  /Users/carlo/octave/msh-1.0.12/msh2m_submesh.m ................. pass    1/1   
  /Users/carlo/octave/msh-1.0.12/msh2m_topological_properties.m .. pass    3/3   
  /Users/carlo/octave/msh-1.0.12/msh3m_geometrical_properties.m .. pass    4/4   
  /Users/carlo/octave/msh-1.0.12/msh3m_join_structured_mesh.m .... pass    4/4   
  /Users/carlo/octave/msh-1.0.12/msh3m_nodes_on_faces.m .......... pass    4/4   
  /Users/carlo/octave/msh-1.0.12/msh3m_structured_mesh.m ......... pass    5/5   
  /Users/carlo/octave/msh-1.0.12/msh3m_submesh.m ................. pass    3/3   

Fixed test scripts:


Summary:

  PASS                               29
  FAIL                                0

See the file /Users/carlo/Documents/_Programmi/Miei/octave/octave-packages-github/packages/packages/fntests.log for additional details.

9 (of 21) .m files have no tests.

Please help improve Octave by contributing tests for these files
(see the list in the file /Users/carlo/Documents/_Programmi/Miei/octave/octave-packages-github/packages/packages/fntests.log).

>> exit
```

**Comment by siko1056** [comment]
Yes, many thanks, looks all good to me now.

**Pull request merged**
