### PR TITLE
Update fuzzy-logic-toolkit.yaml

### PR DESCRIPTION
**Pull request by lmarkowsky**
Added section for release 0.5.0 of the fuzzy-logic-toolkit.

### CODE REVIEW

**Comment by mmuetzel** [comment]
Thank you for updating the package.

Just a couple of remarks and questions:

Are you the original maintainer of the package that was hosted on sourceforge?

It looks like the checksum doesn't match the tarball that is downloaded by the CI. Does the link point to the correct tarball? Or does the checksum need to be changed?

It is a bit unusual to host the release tarballs in a different repository than the GitHub repository with the sources. That is assuming that the sources are here: https://github.com/lmarkowsky/fuzzy-logic-toolkit
And the corresponding release tarballs are here: https://github.com/lmarkowsky/fuzzy-logic-toolkit-releases
More typically, package maintainers would tag a commit with a label for a release and use the "Release" feature of GitHub to host the tarballs.
Would you like to adapt your release process to that?

**Comment by lmarkowsky** [comment]
Thanks for your comments. Yes, I'm the original author and maintainer of the package, which has been hosted on Octave Forge since 2011. This is my first attempt to update the package in several years. 

The link points at the directory containing the tarball, not at the tarball itself. Perhaps that's the source of the discrepancy. I'm still getting the same checksum (for a local copy of the tarball) on my laptop.

I'd definitely like to adapt my release process to the best current practice. Thanks for your comments, and I will follow your advice.

**Comment by mmuetzel** [comment]
I've noticed that you tagged the release in the GitHub repository. So, I went ahead and updated the yaml file accordingly.
I hope that is ok with you.

If you don't mind, I'd like to merge this PR with these changes. Is that ok?

**Comment by mmuetzel** [comment]
Oops. Looks like we crossed.

In the last commit the .yaml file ended up in the wrong directory. I've moved it to the correct one.

Ok to merge?

**Comment by lmarkowsky** [comment]
Good morning. Sure. Thank you.

**Comment by lmarkowsky** [comment]
Is it correct now? I think I understand what I did wrong last time, but if not, please let me know.

**Comment by mmuetzel** [comment]
It's looking good to me. 👍
I guess the next updates will be easier because you can use the last version as a template.

FYI: An announcement about the update is generated automatically on the Octave discourse forum shortly (approx. 30 minutes) after the update is merged in this repository. For the latest announcement, see:
https://octave.discourse.group/t/fuzzy-logic-toolkit-0-5-1-released/5618

An additional side note: Built-in self tests (BISTs) can be run with `pkg test fuzzy-logic-toolkit`. There is CI for every PR in this repository that tries to run those tests on the new release tarball.
Currently, the fuzzy-logic-toolkit doesn't have any BISTs. These can be added in `%!test` blocks (usually at the end of the .m file for a function).
See, e.g., the tests for the `polyeig.m` file in core Octave:
https://hg.savannah.gnu.org/hgweb/octave/file/a56b2283959a/scripts/polynomial/polyeig.m#l92

Would you like to consider adding some tests to (some of) your functions? That would help to catch packaging, compatibility, or other issues more easily.

**Comment by lmarkowsky** [comment]
Thank you! Yes, adding tests is definitely on my to-do list. Right now, there are embedded and standalone demos that have served as (not automatically run) tests, and adding tests is high on my to-do list. Thanks again for your help and advice.

**Pull request merged**
