### PR TITLE
ADD - pkg fileio

### PR DESCRIPTION
**Pull request by tiborauer**

### CODE REVIEW

**Comment by tiborauer** [comment]
This PR publishes the package "fileio"

**Comment by siko1056** [comment]
@tiborauer, could the release year be rather 2023 not 2022?

**Comment by tiborauer** [comment]
Yes. Thank you for noticing! I have updated the file in my repo.

**Comment by tiborauer** [comment]
Shall I open another PR?

**Comment by siko1056** [comment]
Yes, please open one and you can merge it yourself.  I invite you to the Octave group.

**Pull request merged**
