### PR TITLE
Add mqtt.yaml

### PR DESCRIPTION
**Pull request by lostbard**
New package mqtt

### CODE REVIEW

**Comment by lostbard** [comment]
ok - so since file name is octave-mqtt - permalink should be octave-mqtt  or mqtt ?

**Comment by siko1056** [comment]
The file name is `packages/mqtt.yaml`.  Thus `mqtt/` should be the permalink.

**Comment by siko1056** [comment]
The download URL seems not pointing to the actual tarball <https://downloads.sourceforge.net/project/octave-mqtt/v0.0.q/octave-mqtt-0.0.1.tar.gz':>

**Comment by lostbard** [comment]
ah ... my fault then :)
Will fix

**Pull request merged**
