### PR TITLE
Update statistics.yaml

### PR DESCRIPTION
**Pull request by pr0m1th3as**

### CODE REVIEW

**Comment by mmuetzel** [comment]
Did you re-upload the package without bumping the version number?

**Comment by pr0m1th3as** [comment]
Yes, is this a problem? There were some errors in `var` and `std` functions that were spotted by @nrjank and were fixed and pushed within a few hours of the 1.5.2 release, so I considered it is best to replace the release tar without bumping the version number to 1.5.3.

**Comment by mmuetzel** [comment]
In general, released tarballs should never change after a release. If they do, the version number should be bumped even if the changes are miniscule.
The current case lead to the MXE Octave build stalling for a couple of days because the release tarball no longer matched the original checksum.
The same might have happened for the package version in Debian or other distributions.

**Comment by pr0m1th3as** [comment]
I apologize for this inconvenience. I was not aware that this would cause such trouble. I will keep this in mind from now on. Thanks a lot for pointing this out.

**Pull request merged**
